use crate::error::{Error, Result};
use crate::vertex_ai::models::{Content, GenerateContentRequest, GenerateContentResponse, Part};
use google_cloud_auth::credentials;
use reqwest::Client;

pub struct VertexAiClient {
    client: Client,
    #[allow(dead_code)]
    project_id: String,
    #[allow(dead_code)]
    location: String,
    model: String,
    base_url: String,
}

impl VertexAiClient {
    pub fn new(project_id: &str, location: &str, model: &str) -> Result<Self> {
        let client = Client::new();
        let base_url = format!(
            "https://{}-aiplatform.googleapis.com/v1/projects/{}/locations/{}/publishers/google/models",
            location, project_id, location
        );

        Ok(Self {
            client,
            project_id: project_id.to_string(),
            location: location.to_string(),
            model: model.to_string(),
            base_url,
        })
    }

    pub async fn generate_feedback(&self, content: &str, prompt: &str) -> Result<String> {
        let url = format!("{}/{}:generateContent", self.base_url, self.model);

        // Application Default Credentials (ADC) を使用して認証情報を取得
        let credential = credentials::create_access_token_credential()
            .await
            .map_err(|e| Error::VertexAi(format!("Failed to get ADC: {}", e)))?;

        // アクセストークンを取得
        let token = credential
            .get_token()
            .await
            .map_err(|e| Error::VertexAi(format!("Failed to get access token: {}", e)))?;

        // Create the request payload
        let request = GenerateContentRequest {
            contents: vec![Content {
                role: "user".to_string(),
                parts: vec![Part {
                    text: format!("{}\n\n{}", prompt, content),
                }],
            }],
        };

        // Send the request to Vertex AI with authorization header
        let response = self
            .client
            .post(&url)
            .bearer_auth(token.token)
            .json(&request)
            .send()
            .await
            .map_err(|e| Error::VertexAi(format!("Failed to send request to Vertex AI: {}", e)))?;

        if !response.status().is_success() {
            let status = response.status();
            let error_text = response
                .text()
                .await
                .unwrap_or_else(|_| "Unknown error".to_string());
            return Err(Error::VertexAi(format!(
                "Vertex AI request failed. Status: {}, Error: {}",
                status, error_text
            )));
        }

        // Parse the response
        let response_body: GenerateContentResponse = response
            .json()
            .await
            .map_err(|e| Error::VertexAi(format!("Failed to parse Vertex AI response: {}", e)))?;

        // Extract the generated text
        if let Some(candidate) = response_body.candidates.first() {
            if let Some(part) = candidate.content.parts.first() {
                return Ok(part.text.clone());
            }
        }

        Err(Error::VertexAi(
            "No content generated by Vertex AI".to_string(),
        ))
    }
}
